template: |
  ## What's Changed

  $CHANGES
references:
- "main"
- "master"
tag-template: "v$RESOLVED_VERSION"
name-template: "v$RESOLVED_VERSION"
change-template: |
  - $TITLE @$AUTHOR (#$NUMBER)
    $BODY
header: |
  # :mega: Version $RESOLVED_VERSION
categories:
- title: '🚀 Features'
  collapse-after: 10
  labels:
  - 'feature'
  - 'enhancement'
  - 'feat'
- title: '🐛 Bug Fixes'
  collapse-after: 10
  labels:
  - 'bug'
  - 'fix'
  - 'bugfix'
- title: '🧰 Maintenance'
  collapse-after: 10
  labels:
  - 'chore'
  - 'refactor'
  - 'maintenance'
- title: '📚 Documentation'
  collapse-after: 10
  labels:
  - 'docs'
  - 'documentation'
- title: '🧪 Tests'
  collapse-after: 10
  labels:
  - 'test'
  - 'tests'
  - 'testing'
- title: '🔧 Patches'
  collapse-after: 10
  labels:
  - 'patch'
- title: '🏷️ Version Dependency Update'
  collapse-after: 10
  labels:
  - 'version dependency update'
- title: '🚨 Breaking Changes'
  labels:
  - 'breaking'
  - 'major'
- title: '📦 New Resource Added'
  labels:
  - 'new resource added'

version-resolver:
  default: patch
  major:
    labels:
    - 'breaking'
    - 'major'
  minor:
    labels:
    - 'minor'
  patch:
    labels:
    - 'feature'
    - 'bug'
    - 'fix'
    - 'bugfix'
    - 'patch'
    - 'hotfix'
    - 'new resource added'
    - 'version dependency update'
    - 'enhancement'
    - 'feat'
